service: beerjs

provider:
  name: google
  runtime: nodejs
  project: beerjs-170301
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  getBeer:
    handler: getBeer
    memorySize: 128
    timeout: 30s
    events:
      - http: path
